plugins:
  - rubocop-rake
  - rubocop-minitest

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "gemfiles/**/*"
    - "vendor/**/*"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
